// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKeRZ-hgdQ9xTrQ-KruKg-OB-CMLzk3_k',
    appId: '1:824756150035:web:13f0e2488f734268c404e6',
    messagingSenderId: '824756150035',
    projectId: 'mutxamelcf-4b1dd',
    authDomain: 'mutxamelcf-4b1dd.firebaseapp.com',
    storageBucket: 'mutxamelcf-4b1dd.firebasestorage.app',
    measurementId: 'G-FM565GMWN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLKt7TL3mQSXEMxeJvqRzxnJYT1ES82Yg',
    appId: '1:824756150035:android:3f83d48d19dcb8d6c404e6',
    messagingSenderId: '824756150035',
    projectId: 'mutxamelcf-4b1dd',
    storageBucket: 'mutxamelcf-4b1dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRd0X_qpy2eQSv56scyxVxmtccS8JcETc',
    appId: '1:824756150035:ios:4d6fc2a6c9449939c404e6',
    messagingSenderId: '824756150035',
    projectId: 'mutxamelcf-4b1dd',
    storageBucket: 'mutxamelcf-4b1dd.firebasestorage.app',
    iosBundleId: 'com.example.appmtx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRd0X_qpy2eQSv56scyxVxmtccS8JcETc',
    appId: '1:824756150035:ios:4d6fc2a6c9449939c404e6',
    messagingSenderId: '824756150035',
    projectId: 'mutxamelcf-4b1dd',
    storageBucket: 'mutxamelcf-4b1dd.firebasestorage.app',
    iosBundleId: 'com.example.appmtx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKeRZ-hgdQ9xTrQ-KruKg-OB-CMLzk3_k',
    appId: '1:824756150035:web:336b1fdffe8fbff8c404e6',
    messagingSenderId: '824756150035',
    projectId: 'mutxamelcf-4b1dd',
    authDomain: 'mutxamelcf-4b1dd.firebaseapp.com',
    storageBucket: 'mutxamelcf-4b1dd.firebasestorage.app',
    measurementId: 'G-9VLNN0WJKX',
  );
}
